jQuery(document).ready (event) ->
  isAnimating = false
  newLocation = ''
  $nav = $('.nav-item')
  $header = $('#header nav')

  $hello = $('#hello')
  $hello.addClass 'active'


  # init controller
  controller = new (ScrollMagic.Controller)
  # build scenes
  # new (ScrollMagic.Scene)(triggerElement: '#hello').setClassToggle('#hello', 'active').addTo controller
  # new (ScrollMagic.Scene)(triggerElement: '#about').setClassToggle('#about', 'active').addTo controller
  new (ScrollMagic.Scene)(triggerElement: '#work').setClassToggle('#work', 'active').addTo controller
  new (ScrollMagic.Scene)(triggerElement: '#contact', offset: -50).setClassToggle('#contact', 'active').addTo controller
  new (ScrollMagic.Scene)(triggerElement: '#about', offset: -100).addTo(controller).on('enter', (e) ->
    $('#about').addClass 'active'
  )

  # change behaviour of controller to animate scroll instead of jump
  controller.scrollTo (newpos) ->
    TweenMax.to window, 0.75, scrollTo: y: newpos
    return
  #  bind scroll to anchor links
  $(document).on 'click', 'a[href^=\'#\']', (e) ->
    id = $(this).attr('href')
    console.log 'id', id
    if $(id).length > 0
      e.preventDefault()
      # trigger scroll
      controller.scrollTo id
      # if supported by the browser we can even update the URL.
      if window.history and window.history.pushState
        history.pushState '', document.title, id
    return

  # ---
  # generated by js2coffee 2.1.0

  changePage = (url, bool, $click) =>
    isAnimating = true
    # trigger page animation
    $('body').addClass 'page-is-changing'
    $('.cd-loading-bar').one 'webkitTransitionEnd otransitionend oTransitionEnd msTransitionEnd transitionend', ->
      loadNewContent url, bool, $click
      newLocation = url
      $('.cd-loading-bar').off 'webkitTransitionEnd otransitionend oTransitionEnd msTransitionEnd transitionend'

    #if browser doesn't support CSS transitions
    if !transitionsSupported()
      loadNewContent url, bool, $click
      newLocation = url

  loadNewContent = (url, bool, $click) =>
    url = if '' == url then 'index' else url
    newSection = 'cd-' + url.replace('.html', '')
    section = $('<div class="cd-main-content ' + newSection + '"></div>')
    section.load url + ' .cd-main-content > *', (event) =>
      # load new content and replace <main> content with the new one
      $('main').html section
      #if browser doesn't support CSS transitions - dont wait for the end of transitions
      delay = if transitionsSupported() then 1200 else 0
      setTimeout (=>
        #wait for the end of the transition on the loading bar before revealing the new content
        if section.hasClass('cd-template') then $('body').addClass('cd-template') else $('body').removeClass('cd-template')
        $nav.removeClass 'active'
        $active = $(".nav-item[href='#{url}']")
        $active.addClass 'active'
        if $click.hasClass 'index'
          $header.addClass 'hide'
        else
          $header.removeClass 'hide'
        $('body').removeClass 'page-is-changing'
        $('.cd-loading-bar').one 'webkitTransitionEnd otransitionend oTransitionEnd msTransitionEnd transitionend', ->
          isAnimating = false
          $('.cd-loading-bar').off 'webkitTransitionEnd otransitionend oTransitionEnd msTransitionEnd transitionend'

        if !transitionsSupported()
          isAnimating = false

      ), delay
      if url != window.location and bool
        #add the new page to the window.history
        #if the new page was triggered by a 'popstate' event, don't add it
        window.history.pushState { path: url }, '', url

  transitionsSupported = ->
    $('html').hasClass 'csstransitions'

  firstLoad = false
  #trigger smooth transition from the actual page to the new one
  $('body').on 'click', '[data-type="page-transition"]', (event) ->
    event.preventDefault()
    #detect which page has been selected
    $click = $(event.currentTarget)

    unless $click.hasClass 'active'
      newPage = $(this).attr('href')

      #if the page is not already being animated - trigger animation
      if !isAnimating
        changePage newPage, true, $click
    firstLoad = true

  #detect the 'popstate' event - e.g. user clicking the back button
  $(window).on 'popstate', ->
    if firstLoad

      ###
      Safari emits a popstate event on page load - check if firstLoad is true before animating
      if it's false - the page has just been loaded
      ###

      newPageArray = location.pathname.split('/')
      newPage = newPageArray[newPageArray.length - 1]
      if !isAnimating and newLocation != newPage
        changePage newPage, false, $('.index')
    firstLoad = true